<?php

declare(strict_types=1);

require __DIR__ . '/env.php';

$params = require __DIR__ . '/params.php';
$db = require __DIR__ . '/test_db.php';

/**
 * Application configuration shared by all test types.
 */
return [
    'id' => 'ownlane-api-tests',
    'basePath' => dirname(__DIR__),
    'bootstrap' => [
        \app\tests\Support\MailerBootstrap::class,
    ],
    'aliases' => [
        '@bower' => '@vendor/bower-asset',
        '@npm' => '@vendor/npm-asset',
    ],
    'language' => 'en-GB',
    'components' => [
        'db' => $db,
        'cache' => [
            'class' => \yii\caching\ArrayCache::class,
        ],
        'stripeGateway' => static fn () => new \app\components\payments\FakeStripeGateway(),
        'mailer' => [
            'class' => \yii\symfonymailer\Mailer::class,
            'messageClass' => \yii\symfonymailer\Message::class,
            'useFileTransport' => true,
            'viewPath' => '@app/mail',
        ],
        'assetManager' => [
            'basePath' => __DIR__ . '/../web/assets',
        ],
        'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => true,
            'enableStrictParsing' => false,
            'rules' => [
                'GET health' => 'health/index',
                'POST auth/register' => 'auth/register',
                'POST auth/login' => 'auth/login',
                'POST auth/logout' => 'auth/logout',
                'GET auth/me' => 'auth/me',
                'POST auth/password-reset/request' => 'auth/password-reset-request',
                'GET auth/password-reset/peek' => 'auth/password-reset-peek',
                'POST auth/password-reset/confirm' => 'auth/password-reset-confirm',
                'GET learners' => 'learner/index',
                'GET learners/waiting' => 'learner/waiting',
                'GET learners/report' => 'learner/report',
                'POST learners' => 'learner/create',
                'GET learners/import/template' => 'learner/import-template',
                'POST learners/import/preview' => 'learner/import-preview',
                'POST learners/import/confirm' => 'learner/import-confirm',
                'GET intakes' => 'intake/index',
                'POST intakes' => 'intake/create',
                'GET intakes/<id:\d+>' => 'intake/review',
                'POST intakes/<id:\d+>/accept' => 'intake/accept',
                'POST intakes/<id:\d+>/waitlist' => 'intake/waitlist',
                'POST intakes/<id:\d+>/revoke' => 'intake/revoke',
                'GET intake/peek' => 'intake/peek',
                'GET intake/terms' => 'intake/terms',
                'POST intake/submit' => 'intake/submit',
                'GET learners/<id:\d+>' => 'learner/view',
                'PUT learners/<id:\d+>' => 'learner/update',
                'PATCH learners/<id:\d+>' => 'learner/update',
                'POST learners/<id:\d+>/archive' => 'learner/archive',
                'POST learners/<id:\d+>/status' => 'learner/status',
                'GET learners/<id:\d+>/booking-suggestion' => 'learner/booking-suggestion',
                'GET learners/<id:\d+>/availability' => 'learner/availability',
                'PUT learners/<id:\d+>/availability' => 'learner/replace-availability',
                'GET learners/<id:\d+>/locations' => 'learner-location/index',
                'POST learners/<id:\d+>/locations' => 'learner-location/create',
                'PUT learners/<learnerId:\d+>/locations/<id:\d+>' => 'learner-location/update',
                'PATCH learners/<learnerId:\d+>/locations/<id:\d+>' => 'learner-location/update',
                'DELETE learners/<learnerId:\d+>/locations/<id:\d+>' => 'learner-location/delete',
                'POST learners/<learnerId:\d+>/locations/<id:\d+>/default' => 'learner-location/set-default',
                'GET learners/<id:\d+>/finance' => 'finance/panel',
                'POST learners/<id:\d+>/packages' => 'finance/create-package',
                'POST learners/<id:\d+>/payments' => 'finance/record-payment',
                'POST payments/<id:\d+>/void' => 'finance/void-payment',
                'POST packages/<id:\d+>/void' => 'finance/void-package',
                'GET business/overview' => 'business/overview',
                'GET business/export' => 'business/export',
                'POST business/expenses' => 'business/create-expense',
                'POST business/expenses/<id:\d+>/void' => 'business/void-expense',
                'GET settings' => 'settings/index',
                'PUT settings' => 'settings/update',
                'PATCH settings' => 'settings/update',
                'POST learners/<id:\d+>/portal-invite' => 'learner/portal-invite',
                'GET learners/<id:\d+>/portal-status' => 'learner/portal-status',
                'GET portal/invite' => 'portal/peek-invite',
                'POST portal/activate' => 'portal/activate',
                'POST portal/login' => 'portal/login',
                'POST portal/logout' => 'portal/logout',
                'GET portal/me' => 'portal/me',
                'POST portal/password-reset/request' => 'portal/password-reset-request',
                'GET portal/password-reset/peek' => 'portal/password-reset-peek',
                'POST portal/password-reset/confirm' => 'portal/password-reset-confirm',
                'GET portal/home' => 'portal/home',
                'GET portal/places' => 'portal/locations',
                'POST portal/places' => 'portal/location-create',
                'PUT portal/places/<id:\d+>' => 'portal/location-update',
                'PATCH portal/places/<id:\d+>' => 'portal/location-update',
                'DELETE portal/places/<id:\d+>' => 'portal/location-delete',
                'POST portal/places/<id:\d+>/default' => 'portal/location-default',
                'GET portal/lessons/<id:\d+>/messages' => 'portal/lesson-messages',
                'POST portal/lessons/<id:\d+>/messages' => 'portal/lesson-post-message',
                'PUT portal/lessons/<id:\d+>/pickup' => 'portal/lesson-pickup',
                'PATCH portal/lessons/<id:\d+>/pickup' => 'portal/lesson-pickup',
                'PUT portal/lessons/<id:\d+>/focus-tags' => 'portal/lesson-focus-tags',
                'PATCH portal/lessons/<id:\d+>/focus-tags' => 'portal/lesson-focus-tags',
                'GET lessons' => 'lesson/index',
                'GET lessons/diary' => 'lesson/diary',
                'POST lessons/travel-check' => 'lesson/travel-check',
                'POST lessons/recurring/preview' => 'lesson/recurring-preview',
                'POST lessons/recurring' => 'lesson/recurring-create',
                'POST lessons' => 'lesson/create',
                'GET lessons/<id:\d+>/context' => 'lesson/context',
                'GET lessons/<id:\d+>/messages' => 'lesson/messages',
                'POST lessons/<id:\d+>/messages' => 'lesson/post-message',
                'POST lessons/<id:\d+>/acknowledge-pickup' => 'lesson/acknowledge-pickup',
                'GET lessons/<id:\d+>' => 'lesson/view',
                'PUT lessons/<id:\d+>' => 'lesson/update',
                'PATCH lessons/<id:\d+>' => 'lesson/update',
                'POST lessons/<id:\d+>/cancel' => 'lesson/cancel',
                'POST lessons/<id:\d+>/settle-cancellation' => 'lesson/settle-cancellation',
                'POST lessons/<id:\d+>/complete' => 'lesson/complete',
                'POST lessons/<id:\d+>/no-show' => 'lesson/no-show',
                'POST diary-blocks' => 'diary-block/create',
                'PUT diary-blocks/<id:\d+>' => 'diary-block/update',
                'PATCH diary-blocks/<id:\d+>' => 'diary-block/update',
                'DELETE diary-blocks/<id:\d+>' => 'diary-block/delete',
                'POST diary-blocks/<id:\d+>/delete' => 'diary-block/delete',
                'POST lessons/<id:\d+>/mock-tests' => 'mock-test/start-lesson',
                'GET mock-tests/catalogue' => 'mock-test/catalogue',
                'GET mock-tests/<id:\d+>' => 'mock-test/view',
                'POST mock-tests/<id:\d+>/faults' => 'mock-test/record-fault',
                'POST mock-tests/<id:\d+>/faults/<faultId:\d+>/undo' => 'mock-test/undo-fault',
                'POST mock-tests/<id:\d+>/finish' => 'mock-test/finish',
                'POST learners/<id:\d+>/mock-tests' => 'mock-test/start-learner',
                'GET learners/<id:\d+>/mock-tests' => 'mock-test/learner-list',
                'GET practical-tests/catalogue' => 'practical-test/catalogue',
                'GET practical-tests/stats' => 'practical-test/stats',
                'GET practical-tests' => 'practical-test/index',
                'POST practical-tests' => 'practical-test/create',
                'GET practical-tests/<id:\d+>' => 'practical-test/view',
                'PUT practical-tests/<id:\d+>' => 'practical-test/update',
                'PATCH practical-tests/<id:\d+>' => 'practical-test/update',
                'DELETE practical-tests/<id:\d+>' => 'practical-test/delete',
                'POST practical-tests/<id:\d+>/delete' => 'practical-test/delete',
                'GET learners/<id:\d+>/practical-tests' => 'practical-test/learner-list',
                'GET today' => 'today/index',
                'GET day-wrap' => 'day-wrap/index',
            ],
        ],
        'user' => [
            'class' => \yii\web\User::class,
            'identityClass' => \app\models\User::class,
            'enableAutoLogin' => false,
            'enableSession' => true,
        ],
        'portalUser' => [
            'class' => \yii\web\User::class,
            'identityClass' => \app\models\LearnerPortalAccount::class,
            'enableAutoLogin' => false,
            'enableSession' => true,
            'idParam' => '__portalId',
            'authTimeoutParam' => '__portalExpire',
            'absoluteAuthTimeoutParam' => '__portalAbsoluteExpire',
            'returnUrlParam' => '__portalReturnUrl',
            'identityCookie' => [
                'name' => '_portal_identity',
                'httpOnly' => true,
                'sameSite' => \yii\web\Cookie::SAME_SITE_LAX,
            ],
        ],
        'companionUser' => [
            'class' => \yii\web\User::class,
            'identityClass' => \app\models\CompanionAccount::class,
            'enableAutoLogin' => false,
            'enableSession' => true,
            'idParam' => '__companionId',
            'authTimeoutParam' => '__companionExpire',
            'absoluteAuthTimeoutParam' => '__companionAbsoluteExpire',
            'returnUrlParam' => '__companionReturnUrl',
            'identityCookie' => [
                'name' => '_companion_identity',
                'httpOnly' => true,
                'sameSite' => \yii\web\Cookie::SAME_SITE_LAX,
            ],
        ],
        'session' => [
            'class' => \yii\web\Session::class,
        ],
        'request' => [
            'cookieValidationKey' => 'test',
            'enableCsrfValidation' => false,
            'parsers' => [
                'application/json' => \yii\web\JsonParser::class,
            ],
        ],
        'response' => [
            'format' => \yii\web\Response::FORMAT_JSON,
            'charset' => 'UTF-8',
        ],
    ],
    'params' => $params,
];
