<?php

declare(strict_types=1);

$params = require __DIR__ . '/params.php';
$db = require __DIR__ . '/db.php';

$corsOrigins = array_values(array_filter(array_map(
    'trim',
    explode(',', (string) (getenv('CORS_ORIGIN') ?: 'http://localhost:3000')),
)));

$config = [
    'id' => 'ownlane-api',
    'name' => 'OwnLane API',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],
    'aliases' => [
        '@bower' => '@vendor/bower-asset',
        '@npm' => '@vendor/npm-asset',
    ],
    'components' => [
        'request' => [
            'cookieValidationKey' => getenv('COOKIE_VALIDATION_KEY') ?: 'change-me',
            'parsers' => [
                'application/json' => \yii\web\JsonParser::class,
            ],
            // Enable cookie auth across Nuxt (localhost:3000) → API (localhost:8080) later
            'csrfParam' => '_csrf',
        ],
        'response' => [
            'format' => \yii\web\Response::FORMAT_JSON,
            'charset' => 'UTF-8',
            'on beforeSend' => static function ($event) {
                /** @var \yii\web\Response $response */
                $response = $event->sender;
                $response->headers->set('X-Powered-By', 'OwnLane');
            },
        ],
        'cache' => [
            'class' => \yii\caching\FileCache::class,
        ],
        'user' => [
            'class' => \yii\web\User::class,
            'identityClass' => \app\models\User::class,
            'enableAutoLogin' => false,
            'enableSession' => true,
            'identityCookie' => [
                'name' => '_identity',
                'httpOnly' => true,
                'sameSite' => \yii\web\Cookie::SAME_SITE_LAX,
            ],
        ],
        'portalUser' => [
            'class' => \yii\web\User::class,
            'identityClass' => \app\models\LearnerPortalAccount::class,
            'enableAutoLogin' => false,
            'enableSession' => true,
            'idParam' => '__portalId',
            'authTimeoutParam' => '__portalExpire',
            'absoluteAuthTimeoutParam' => '__portalAbsoluteExpire',
            'returnUrlParam' => '__portalReturnUrl',
            'identityCookie' => [
                'name' => '_portal_identity',
                'httpOnly' => true,
                'sameSite' => \yii\web\Cookie::SAME_SITE_LAX,
            ],
        ],
        'companionUser' => [
            'class' => \yii\web\User::class,
            'identityClass' => \app\models\CompanionAccount::class,
            'enableAutoLogin' => false,
            'enableSession' => true,
            'idParam' => '__companionId',
            'authTimeoutParam' => '__companionExpire',
            'absoluteAuthTimeoutParam' => '__companionAbsoluteExpire',
            'returnUrlParam' => '__companionReturnUrl',
            'identityCookie' => [
                'name' => '_companion_identity',
                'httpOnly' => true,
                'sameSite' => \yii\web\Cookie::SAME_SITE_LAX,
            ],
        ],
        'errorHandler' => [
            'errorAction' => 'health/error',
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => \yii\log\FileTarget::class,
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'db' => $db,
        'mailer' => [
            'class' => \yii\symfonymailer\Mailer::class,
            'viewPath' => '@app/mail',
            'useFileTransport' => !(is_string(getenv('MAIL_DSN')) && trim((string) getenv('MAIL_DSN')) !== ''),
            'transport' => (is_string(getenv('MAIL_DSN')) && trim((string) getenv('MAIL_DSN')) !== '')
                ? ['dsn' => getenv('MAIL_DSN')]
                : [],
        ],
        'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'enableStrictParsing' => false,
            'rules' => [
                'GET health' => 'health/index',
                'POST auth/register' => 'auth/register',
                'POST auth/login' => 'auth/login',
                'POST auth/sign-in' => 'auth/sign-in',
                'POST auth/logout' => 'auth/logout',
                'GET auth/me' => 'auth/me',
                'POST auth/password-reset/request' => 'auth/password-reset-request',
                'GET auth/password-reset/peek' => 'auth/password-reset-peek',
                'POST auth/password-reset/confirm' => 'auth/password-reset-confirm',
                'GET learners' => 'learner/index',
                'GET learners/waiting' => 'learner/waiting',
                'GET learners/report' => 'learner/report',
                'POST learners' => 'learner/create',
                'GET learners/import/template' => 'learner/import-template',
                'POST learners/import/preview' => 'learner/import-preview',
                'POST learners/import/confirm' => 'learner/import-confirm',
                'GET intakes' => 'intake/index',
                'POST intakes' => 'intake/create',
                'GET intakes/<id:\d+>' => 'intake/review',
                'POST intakes/<id:\d+>/accept' => 'intake/accept',
                'POST intakes/<id:\d+>/waitlist' => 'intake/waitlist',
                'POST intakes/<id:\d+>/revoke' => 'intake/revoke',
                'GET intake/peek' => 'intake/peek',
                'GET intake/terms' => 'intake/terms',
                'POST intake/submit' => 'intake/submit',
                'GET learners/<id:\d+>' => 'learner/view',
                'PUT learners/<id:\d+>' => 'learner/update',
                'PATCH learners/<id:\d+>' => 'learner/update',
                'POST learners/<id:\d+>/archive' => 'learner/archive',
                'POST learners/<id:\d+>/status' => 'learner/status',
                'GET learners/<id:\d+>/booking-suggestion' => 'learner/booking-suggestion',
                'GET learners/<id:\d+>/availability' => 'learner/availability',
                'PUT learners/<id:\d+>/availability' => 'learner/replace-availability',
                'GET learners/<id:\d+>/locations' => 'learner-location/index',
                'POST learners/<id:\d+>/locations' => 'learner-location/create',
                'PUT learners/<learnerId:\d+>/locations/<id:\d+>' => 'learner-location/update',
                'PATCH learners/<learnerId:\d+>/locations/<id:\d+>' => 'learner-location/update',
                'DELETE learners/<learnerId:\d+>/locations/<id:\d+>' => 'learner-location/delete',
                'POST learners/<learnerId:\d+>/locations/<id:\d+>/default' => 'learner-location/set-default',
                'GET learners/<id:\d+>/finance' => 'finance/panel',
                'POST learners/<id:\d+>/packages' => 'finance/create-package',
                'POST learners/<id:\d+>/payments' => 'finance/record-payment',
                'POST payments/<id:\d+>/void' => 'finance/void-payment',
                'POST packages/<id:\d+>/void' => 'finance/void-package',
                'GET business/overview' => 'business/overview',
                'GET business/report' => 'business/report',
                'GET business/export' => 'business/export',
                'POST business/expenses' => 'business/create-expense',
                'POST business/expenses/<id:\d+>/void' => 'business/void-expense',
                'POST business/expenses/<id:\d+>/receipt' => 'business/attach-receipt',
                'GET business/expenses/<id:\d+>/receipt' => 'business/receipt',
                'POST business/goals' => 'business/upsert-goal',
                'POST business/goals/delete' => 'business/delete-goal',
                'GET business/vehicles' => 'business/list-vehicles',
                'POST business/vehicles' => 'business/create-vehicle',
                'POST business/vehicles/<id:\d+>' => 'business/update-vehicle',
                'GET business/vehicles/<id:\d+>' => 'business/vehicle-detail',
                'GET business/mileage' => 'business/list-mileage',
                'POST business/mileage' => 'business/create-mileage',
                'POST business/mileage/<id:\d+>/delete' => 'business/delete-mileage',
                'GET settings' => 'settings/index',
                'PUT settings' => 'settings/update',
                'PATCH settings' => 'settings/update',
                'GET services' => 'service/index',
                'POST services' => 'service/create',
                'GET services/<id:\d+>' => 'service/view',
                'PUT services/<id:\d+>' => 'service/update',
                'PATCH services/<id:\d+>' => 'service/update',
                'POST services/<id:\d+>/price-changes' => 'service/price-change',
                'POST services/pricing-rules' => 'service/create-rule',
                'PUT services/pricing-rules/<id:\d+>' => 'service/update-rule',
                'PATCH services/pricing-rules/<id:\d+>' => 'service/update-rule',
                'POST services/pupil-rates' => 'service/create-pupil-rate',
                'PUT services/pupil-rates/<id:\d+>' => 'service/update-pupil-rate',
                'PATCH services/pupil-rates/<id:\d+>' => 'service/update-pupil-rate',
                'POST services/packages' => 'service/create-package',
                'PUT services/packages/<id:\d+>' => 'service/update-package',
                'PATCH services/packages/<id:\d+>' => 'service/update-package',
                'POST settings/calendar/connect' => 'settings/calendar-connect',
                'POST settings/calendar/regenerate' => 'settings/calendar-regenerate',
                'POST settings/calendar/revoke' => 'settings/calendar-revoke',
                'POST settings/calendar/privacy' => 'settings/calendar-privacy',
                'GET search' => 'search/index',
                'GET search/recent' => 'search/recent',
                'GET exports/download' => 'data-export/download',
                'GET exports/accountant-pack' => 'data-export/accountant-pack',
                'GET exports/accountant-summary' => 'data-export/accountant-summary',
                'GET calendar/<token:[a-zA-Z0-9_\-]+>.ics' => 'calendar-feed/feed',
                'GET public/instructors/<slug:[a-z0-9\-]+>' => 'public-profile/profile',
                'GET public/instructors/<slug:[a-z0-9\-]+>/photo' => 'public-profile/photo',
                'GET public/instructors/<slug:[a-z0-9\-]+>/cover' => 'public-profile/cover',
                'GET public/instructors/<slug:[a-z0-9\-]+>/area-check' => 'public-profile/area-check',
                'POST public/instructors/<slug:[a-z0-9\-]+>/enquire' => 'public-profile/enquire',
                'POST public/instructors/<slug:[a-z0-9\-]+>/track' => 'public-profile/track',
                'GET enquiries' => 'enquiry/index',
                'GET enquiries/stats' => 'enquiry/stats',
                'GET enquiries/<id:\d+>' => 'enquiry/view',
                'POST enquiries/<id:\d+>/contact' => 'enquiry/contact',
                'POST enquiries/<id:\d+>/accept' => 'enquiry/accept',
                'POST enquiries/<id:\d+>/decline' => 'enquiry/decline',
                'POST enquiries/<id:\d+>/convert' => 'enquiry/convert',
                'POST enquiries/<id:\d+>/waiting' => 'enquiry/waiting',
                'POST enquiries/<id:\d+>/book' => 'enquiry/book',
                'GET settings/profile' => 'settings/profile',
                'PUT settings/profile' => 'settings/profile-update',
                'PATCH settings/profile' => 'settings/profile-update',
                'POST settings/profile/publish' => 'settings/profile-publish',
                'POST settings/profile/unpublish' => 'settings/profile-unpublish',
                'GET settings/profile/preview' => 'settings/profile-preview',
                'GET settings/profile/photo' => 'settings/profile-photo',
                'POST settings/profile/photo' => 'settings/profile-photo',
                'GET settings/profile/cover' => 'settings/profile-cover',
                'POST settings/profile/cover' => 'settings/profile-cover',
                'GET booking-requests' => 'booking-request/index',
                'POST booking-requests/<id:\d+>/accept' => 'booking-request/accept',
                'POST booking-requests/<id:\d+>/decline' => 'booking-request/decline',
                'POST booking-requests/<id:\d+>/suggest' => 'booking-request/suggest',
                'GET learners/<learnerId:\d+>/booking-availability' => 'booking-request/availability',
                'POST learners/<id:\d+>/portal-invite' => 'learner/portal-invite',
                'GET learners/<id:\d+>/portal-status' => 'learner/portal-status',
                'GET portal/invite' => 'portal/peek-invite',
                'POST portal/activate' => 'portal/activate',
                'POST portal/login' => 'portal/login',
                'POST portal/logout' => 'portal/logout',
                'GET portal/me' => 'portal/me',
                'POST portal/password-reset/request' => 'portal/password-reset-request',
                'GET portal/password-reset/peek' => 'portal/password-reset-peek',
                'POST portal/password-reset/confirm' => 'portal/password-reset-confirm',
                'GET portal/home' => 'portal/home',
                'GET portal/journey' => 'portal/journey',
                'GET portal/progress' => 'portal/progress',
                'GET portal/money' => 'portal/money',
                'GET portal/payments' => 'portal/payments',
                'POST portal/pay/balance' => 'portal/pay-balance',
                'POST portal/pay/package' => 'portal/pay-package',
                'POST portal/pay/booking-hold' => 'portal/pay-booking-hold',
                'POST portal/pay/<token:[a-z0-9]+>/confirm' => 'portal/pay-confirm',
                'POST portal/booking/hold' => 'portal/booking-hold',
                'POST webhooks/stripe' => 'stripe-webhook/handle',
                'GET pay/<token:[a-z0-9]+>' => 'guest-payment/view',
                'POST pay/<token:[a-z0-9]+>/start' => 'guest-payment/start',
                'POST pay/<token:[a-z0-9]+>/confirm' => 'guest-payment/confirm',
                'GET payments/account' => 'payment-account/settings',
                'POST payments/account/onboard' => 'payment-account/onboard',
                'POST payments/account/refresh' => 'payment-account/refresh',
                'POST payments/account/booking-policy' => 'payment-account/booking-policy',
                'GET payments/offerings' => 'payment-account/offerings',
                'POST payments/offerings' => 'payment-account/offerings',
                'PUT payments/offerings/<id:\d+>' => 'payment-account/offering-update',
                'PATCH payments/offerings/<id:\d+>' => 'payment-account/offering-update',
                'POST learners/<learnerId:\d+>/payment-request' => 'payment-account/request-payment',
                'POST payments/<id:\d+>/refund' => 'payment-account/refund',
                'GET payments/<id:\d+>/receipt' => 'payment-account/receipt',
                'GET portal/prepare' => 'portal/prepare',
                'GET portal/lessons/<id:\d+>/recap' => 'portal/recap',
                'GET portal/routes' => 'portal/routes',
                'GET portal/routes/<id:\d+>' => 'portal/route-view',
                'GET portal/learn' => 'portal/learn',
                'GET portal/learn/<slug:[a-z0-9\-]+>' => 'portal/learn-content',
                'GET portal/skills/<code:[a-z0-9_]+>/evidence' => 'portal/skill-evidence',
                'POST portal/skills/<code:[a-z0-9_]+>/self-assessment' => 'portal/self-assessment',
                'GET portal/mocks' => 'portal/mocks',
                'GET portal/mocks/<id:\d+>' => 'portal/mock-view',
                'GET portal/booking/settings' => 'portal/booking-settings',
                'GET portal/booking/availability' => 'portal/booking-availability',
                'GET portal/booking/requests' => 'portal/booking-requests',
                'POST portal/booking/requests' => 'portal/booking-requests',
                'POST portal/booking/requests/<id:\d+>/withdraw' => 'portal/booking-withdraw',
                'POST portal/booking/requests/<id:\d+>/accept-counter' => 'portal/booking-accept-counter',
                'POST portal/lessons/<id:\d+>/cancel' => 'portal/lesson-cancel',
                'GET portal/places' => 'portal/locations',
                'POST portal/places' => 'portal/location-create',
                'PUT portal/places/<id:\d+>' => 'portal/location-update',
                'PATCH portal/places/<id:\d+>' => 'portal/location-update',
                'DELETE portal/places/<id:\d+>' => 'portal/location-delete',
                'POST portal/places/<id:\d+>/default' => 'portal/location-default',
                'GET portal/lessons/<id:\d+>/messages' => 'portal/lesson-messages',
                'POST portal/lessons/<id:\d+>/messages' => 'portal/lesson-post-message',
                'PUT portal/lessons/<id:\d+>/pickup' => 'portal/lesson-pickup',
                'PATCH portal/lessons/<id:\d+>/pickup' => 'portal/lesson-pickup',
                'PUT portal/lessons/<id:\d+>/focus-tags' => 'portal/lesson-focus-tags',
                'PATCH portal/lessons/<id:\d+>/focus-tags' => 'portal/lesson-focus-tags',
                'GET portal/practice' => 'portal/practice-list',
                'POST portal/practice' => 'portal/practice-log',
                'GET portal/lessons/<id:\d+>/resources' => 'portal/lesson-resources',
                'GET portal/lessons/<id:\d+>/playback' => 'portal/playback',
                'POST portal/learn/activity' => 'portal/learn-activity',
                'GET share/<token:[a-zA-Z0-9\-_]+>' => 'share/peek',
                'POST portal/shares' => 'share/create',
                'POST portal/shares/<id:\d+>/revoke' => 'share/revoke',
                'GET teaching/templates' => 'teaching/templates',
                'GET teaching/resources' => 'teaching/index',
                'POST teaching/resources' => 'teaching/create',
                'GET teaching/resources/<id:\d+>' => 'teaching/view',
                'PUT teaching/resources/<id:\d+>' => 'teaching/update',
                'PATCH teaching/resources/<id:\d+>' => 'teaching/update',
                'POST teaching/resources/<id:\d+>/duplicate' => 'teaching/duplicate',
                'POST teaching/resources/<id:\d+>/archive' => 'teaching/archive',
                'GET lessons/<id:\d+>/resources' => 'teaching/lesson-resources',
                'POST lessons/<id:\d+>/resources' => 'teaching/attach-lesson',
                'POST lessons/<id:\d+>/moments' => 'learning/mark-moment',
                'GET lessons/<id:\d+>/moments' => 'learning/lesson-moments',
                'PATCH moments/<id:\d+>' => 'learning/update-moment',
                'PUT moments/<id:\d+>' => 'learning/update-moment',
                'GET learners/<id:\d+>/private-practice' => 'learning/private-practice-since',
                'GET learning/contents' => 'learning/admin-contents',
                'POST learning/contents' => 'learning/admin-save-content',
                'PUT learning/contents/<id:\d+>' => 'learning/admin-update-content',
                'PATCH learning/contents/<id:\d+>' => 'learning/admin-update-content',
                'GET lessons' => 'lesson/index',
                'GET lessons/diary' => 'lesson/diary',
                'POST lessons/travel-check' => 'lesson/travel-check',
                'POST lessons/recurring/preview' => 'lesson/recurring-preview',
                'POST lessons/recurring' => 'lesson/recurring-create',
                'POST lessons' => 'lesson/create',
                'GET lessons/skills' => 'lesson-route/skills',
                'GET lessons/<id:\d+>/route' => 'lesson-route/view',
                'POST lessons/<id:\d+>/route/start' => 'lesson-route/start',
                'POST lessons/<id:\d+>/route/stop' => 'lesson-route/stop',
                'POST lessons/<id:\d+>/route/share' => 'lesson-route/share',
                'POST lessons/<id:\d+>/route/unshare' => 'lesson-route/unshare',
                'POST lessons/<id:\d+>/route/discard' => 'lesson-route/discard',
                'GET lessons/<id:\d+>/context' => 'lesson/context',
                'GET lessons/<id:\d+>/messages' => 'lesson/messages',
                'POST lessons/<id:\d+>/messages' => 'lesson/post-message',
                'POST lessons/<id:\d+>/acknowledge-pickup' => 'lesson/acknowledge-pickup',
                'GET lessons/<id:\d+>' => 'lesson/view',
                'PUT lessons/<id:\d+>' => 'lesson/update',
                'PATCH lessons/<id:\d+>' => 'lesson/update',
                'POST lessons/<id:\d+>/cancel' => 'lesson/cancel',
                'POST lessons/<id:\d+>/settle-cancellation' => 'lesson/settle-cancellation',
                'POST lessons/<id:\d+>/complete' => 'lesson/complete',
                'POST lessons/<id:\d+>/no-show' => 'lesson/no-show',
                'POST diary-blocks' => 'diary-block/create',
                'PUT diary-blocks/<id:\d+>' => 'diary-block/update',
                'PATCH diary-blocks/<id:\d+>' => 'diary-block/update',
                'DELETE diary-blocks/<id:\d+>' => 'diary-block/delete',
                'POST diary-blocks/<id:\d+>/delete' => 'diary-block/delete',
                'POST lessons/<id:\d+>/mock-tests' => 'mock-test/start-lesson',
                'GET mock-tests/catalogue' => 'mock-test/catalogue',
                'GET mock-tests/<id:\d+>' => 'mock-test/view',
                'POST mock-tests/<id:\d+>/faults' => 'mock-test/record-fault',
                'POST mock-tests/<id:\d+>/faults/<faultId:\d+>/undo' => 'mock-test/undo-fault',
                'PATCH mock-tests/<id:\d+>/faults/<faultId:\d+>' => 'mock-test/update-fault',
                'PUT mock-tests/<id:\d+>/faults/<faultId:\d+>' => 'mock-test/update-fault',
                'POST mock-tests/<id:\d+>/finish' => 'mock-test/finish',
                'POST mock-tests/<id:\d+>/abandon' => 'mock-test/abandon',
                'PATCH mock-tests/<id:\d+>' => 'mock-test/update',
                'PUT mock-tests/<id:\d+>' => 'mock-test/update',
                'POST mock-tests/<id:\d+>/apply-next-focus' => 'mock-test/apply-next-focus',
                'POST learners/<id:\d+>/mock-tests' => 'mock-test/start-learner',
                'GET learners/<id:\d+>/mock-tests' => 'mock-test/learner-list',
                'GET learners/<id:\d+>/progress' => 'mock-test/learner-progress',
                'POST learners/<id:\d+>/skills/<skillId:\d+>/rating' => 'mock-test/record-skill-rating',
                'POST learners/<id:\d+>/progress-notes' => 'mock-test/upsert-progress-note',
                'GET learners/<learnerId:\d+>/skills/<code:[a-z0-9_]+>' => 'mock-test/skill-detail',
                'GET practical-tests/catalogue' => 'practical-test/catalogue',
                'GET practical-tests/stats' => 'practical-test/stats',
                'GET practical-tests' => 'practical-test/index',
                'POST practical-tests' => 'practical-test/create',
                'GET practical-tests/<id:\d+>' => 'practical-test/view',
                'PUT practical-tests/<id:\d+>' => 'practical-test/update',
                'PATCH practical-tests/<id:\d+>' => 'practical-test/update',
                'DELETE practical-tests/<id:\d+>' => 'practical-test/delete',
                'POST practical-tests/<id:\d+>/delete' => 'practical-test/delete',
                'GET learners/<id:\d+>/practical-tests' => 'practical-test/learner-list',
                'GET today' => 'today/index',
                'GET day-wrap' => 'day-wrap/index',
                'GET' => 'health/index',
            ],
        ],
        'session' => [
            'class' => \yii\web\Session::class,
            'cookieParams' => [
                'httponly' => true,
                'samesite' => \yii\web\Cookie::SAME_SITE_LAX,
                // Path / so the Nuxt /api proxy receives the session cookie.
                'path' => '/',
            ],
        ],
    ],
    'as corsFilter' => [
        'class' => \yii\filters\Cors::class,
        'cors' => [
            'Origin' => $corsOrigins,
            'Access-Control-Request-Method' => ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
            'Access-Control-Request-Headers' => ['Content-Type', 'Authorization', 'X-Requested-With'],
            'Access-Control-Allow-Credentials' => true,
            'Access-Control-Max-Age' => 86400,
        ],
    ],
    'params' => $params,
];

if (YII_ENV_DEV) {
    $config['bootstrap'][] = 'debug';
    $config['modules']['debug'] = [
        'class' => \yii\debug\Module::class,
        'allowedIPs' => ['127.0.0.1', '::1'],
    ];

    $config['bootstrap'][] = 'gii';
    $config['modules']['gii'] = [
        'class' => \yii\gii\Module::class,
        'allowedIPs' => ['127.0.0.1', '::1'],
    ];
}

return $config;
